/// \file   pwmsim.h
/// \author Bernardo Marques
/// \date   2023-05

#pragma once

#include <stdint.h>
#include "drivers/include/pwm.h"

/// @brief Returns the current duty cycle for a PWM channel
/// @param pwm_channel the channel to retrieve duty cycle
/// @return the duty cycle in % * 100 for the PWM channel
uint16_t pwmsim_getDuty(uint8_t pwm_channel);

/// @brief Returns the value of a signal generated by PWM that is a fraction of another signal
/// @param pwm_channel the channel generating output signal
/// @param sourceSignal the source of the signal
/// @return the value of the output signal generated by the PWM channel in the same units as sourceSignal
uint16_t pwmsim_getRatioSignal(uint8_t pwm_channel, uint16_t sourceSignal);

